[package]
name = "amethyst_unity_2d"
version = "0.1.0"
authors = ["Nathan Perry <avaglir@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = { version = "0.10.0", features = ["nightly"] }
num = "0.2.0"
serde = "1.0.82"
